#Multiplier applied to armor dyeing
# Default: 0.5
# Range: 0.0 ~ 1.7976931348623157E308
applyArmorDyeingMultiplier = 0.5
#Multiplier applied to loot dyeing
# Default: 0.75
# Range: 0.0 ~ 1.7976931348623157E308
applyLootDyeingMultiplier = 0.75
#Scaling factor for logarithmic armor
# Default: 0.6908
# Range: 0.0 ~ 1.7976931348623157E308
logarithmicArmorScalingFactor = 0.6908
#Scaling factor for logarithmic enchantments
# Default: 7.824
# Range: 0.0 ~ 1.7976931348623157E308
logarithmicEnchantmentScalingFactor = 7.824
#Natural armor multiplier
# Default: 1
# Range: > 0
naturalArmorMultiplier = 1
#Multiplier for villager armor
# Default: 0.5
# Range: 0.0 ~ 1.7976931348623157E308
villagerArmorMultiplier = 0.5
#Chance for natural armor enchantments
# Default: 0.5
# Range: 0.0 ~ 1.0
naturalArmorEnchantChance = 0.5
#Chance for natural weapon enchantments
# Default: 0.25
# Range: 0.0 ~ 1.0
naturalWeaponEnchantChance = 0.25
#Allow logarithmic armor scaling
allowLogarithmicArmor = false
#Allow logarithmic enchantments
allowLogarithmicEnchantments = false
#Red value for general color (0-255)
# Default: 255
# Range: 0 ~ 255
R = 255
#Green value for general color (0-255)
# Default: 255
# Range: 0 ~ 255
G = 255
#Blue value for general color (0-255)
# Default: 255
# Range: 0 ~ 255
B = 255
