#Sets the percentage of Life Bits dropped based on the entity's armor value.
# Default: 1.0
# Range: 0.0 ~ 10.0
armorBonusPercentage = 1.0
#Sets the percentage of Life Bits dropped based on the entity's armor toughness value.
# Default: 1.0
# Range: 0.0 ~ 10.0
toughnessBonusPercentage = 1.0
#Minimum chance required for Life Bits to drop.
# Default: 0.1
# Range: 0.0 ~ 1.0
minimumDropPercentage = 0.1
#Bias of the drop percentage. Recommended above minimum drop.
# Default: 0.15
# Range: 0.0 ~ 1.0
biasedTowardsPercentage = 0.15
#Increases drops based on mob's attack damage.
# Default: 0.75
# Range: 0.0 ~ 10.0
mobAttackDamageBonus = 0.75
#Reduces drops based on player's max health.
# Default: 0.5
# Range: 0.0 ~ 10.0
playerHealthPenalty = 0.5
#Reduces drops based on player's armor value.
# Default: 0.5
# Range: 0.0 ~ 10.0
playerArmorPenalty = 0.5
#Reduces drops based on player's armor toughness.
# Default: 0.5
# Range: 0.0 ~ 10.0
playerToughnessPenalty = 0.5
#Reduces drops based on player's attack damage.
# Default: 0.375
# Range: 0.0 ~ 10.0
playerAttackDamagePenalty = 0.375
#Minimum player health before health penalty applies.
# Default: 20.0
# Range: 0.0 ~ 1024.0
playerHealthThreshold = 20.0
#Minimum player armor before armor penalty applies.
# Default: 7.0
# Range: 0.0 ~ 1024.0
playerArmorThreshold = 7.0
#Minimum player armor toughness before toughness penalty applies.
# Default: 0.0
# Range: 0.0 ~ 1024.0
playerToughnessThreshold = 0.0
#Minimum player attack damage before penalty applies.
# Default: 8.0
# Range: 0.0 ~ 1024.0
playerAttackDamageThreshold = 8.0
