#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 05 21:05:57 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=ComplementaryUnbound_r5.8.1 + EuphoriaPatches_1.9.3
